### ISSUE TITLE
CSS Improvements

### ISSUE THREAD

**Issue by diegopvlk** [fthx/dash-in-panel#6]
Too lazy to open a PR right now :P but here are some css suggestions:

- Simplify a bit
- Use transparent border instead of margin so the icon is activatable at the edge of panel
- Use box-shadow instead of background-color so the transparent border can work
- Add transition so we can have fade on hover
- Use gray instead of white so the hover effect and separator is visible on light and dark style

```css
.dash-in-panel-icon,
.dash-in-panel-show-apps-button {
  padding: 0 3px;

  border: 2px solid transparent;
  border-left-width: 1px;
  border-right-width: 1px;
  border-radius: 6px;

  transition-duration: 150ms;
}

.dash-in-panel-show-apps-button {
  margin-right: 0px;
  margin-left: 16px;
}

.dash-in-panel-icon:hover,
.dash-in-panel-show-apps-button:hover {
  box-shadow: 0 0 0 rgba(142, 142, 142, 0.35);
}

.dash-in-panel-icon-colored-dot {
  background-color: -st-accent-color;
}

.dash-in-panel-separator {
  margin-right: 8px;
  margin-left: 8px;
  width: 1px;
  background-color: rgba(142, 142, 142, 0.75);
}
```
